/* Job Terminator site dictionaries: Arabic (default, RTL) + English (LTR).
   To add a language: copy the "en" block, translate values, keep keys. */
const I18N = {
ar: {
"meta.title": "Job Terminator — نظام التقديم التلقائي على الوظائف | نسخة ويندوز",
"meta.desc": "Job Terminator يبحث في مواقع التوظيف وقنوات تيليجرام، يطابق الوظائف مع سيرتك الذاتية، يولّد سيرة مخصصة لكل وظيفة، ويرسل من بريدك — بترخيص لجهاز واحد وبيانات مشفّرة على جهازك.",
"brand.sub": "للويندوز",
"nav.label": "التنقل الرئيسي",
"nav.features": "المميزات",
"nav.how": "طريقة التشغيل",
"nav.pricing": "الترخيص",
"nav.download": "التحميل",
"nav.faq": "الأسئلة الشائعة",
"nav.cta": "اطلب الترخيص",
"nav.toggle": "القائمة",
"hero.eyebrow": "نسخة ويندوز مرخّصة — جهاز واحد",
"hero.title": "قدّم على الوظائف المناسبة لك، <span class=\"accent\">تلقائيًا كل يوم</span>",
"hero.lead": "Job Terminator يبحث في مواقع التوظيف وقنوات تيليجرام الخاصة بك، يختار الوظائف المطابقة لسيرتك، يولّد سيرة مخصصة لكل وظيفة، ويرسل من بريدك الإلكتروني. بياناتك ومفاتيحك مشفّرة على جهازك ولا تغادره أبدًا.",
"hero.cta1": "احصل على مفتاح الترخيص",
"hero.cta2": "تحميل نسخة ويندوز",
"hero.meta1": "Windows 10 / 11 ‏(64-bit)",
"hero.meta2": "تفعيل أوفلاين بمفتاح لجهاز واحد",
"hero.meta3": "بدون اشتراك شهري في البرنامج",
"mock.title": "Job Terminator — لوحة التحكم",
"mock.s1": "البحث", "mock.s2": "المطابقة", "mock.s3": "الإرسال",
"mock.s4": "السجل", "mock.s5": "الإعدادات",
"mock.st1": "وظيفة اليوم", "mock.st2": "مطابقة قوية", "mock.st3": "تم إرسالها",
"mock.c1": "مطابقة 87%", "mock.c2": "مطابقة 76%",
"mock.c3": "تم الإرسال", "mock.c4": "مستبعدة",
"strip.label": "يعمل مع أدواتك الحالية",
"strip.more": "+ 4 مواقع أخرى",
"kicker.features": "<span class=\"kicker-num\">٠١</span>ماذا يفعل البرنامج",
"kicker.how": "<span class=\"kicker-num\">٠٢</span>من التثبيت إلى أول إرسال",
"kicker.pricing": "<span class=\"kicker-num\">٠٣</span>الترخيص والأسعار",
"kicker.download": "<span class=\"kicker-num\">٠٤</span>التحميل والتثبيت",
"kicker.faq": "<span class=\"kicker-num\">٠٥</span>الأسئلة الشائعة",
"features.h2": "دورة التقديم كاملة، من البحث حتى الإرسال",
"features.sub": "ست وحدات تعمل معًا. تضبطها مرة واحدة من الإعدادات، ثم تعمل يوميًا بضغطة واحدة.",
"features.f1t": "بحث شامل في مواقع التوظيف",
"features.f1d": "مسح تلقائي لعشرة مواقع توظيف بالكلمات المفتاحية والمواقع التي تحددها، مع منع التكرار وحفظ نتائج كل بحث.",
"features.f2t": "التقاط وظائف تيليجرام",
"features.f2d": "يربط قنواتك ومجموعاتك بحسابك الخاص ويلتقط الإعلانات المنشورة فيها أولًا بأول بنفس دورة العمل.",
"features.f3t": "مطابقة ذكية مع سيرتك",
"features.f3d": "درجة توافق لكل وظيفة مع عتبة قابلة للضبط واستبعاد تلقائي للمستويات والتخصصات غير المناسبة قبل أي إرسال.",
"features.f4t": "سيرة مخصصة لكل وظيفة",
"features.f4d": "توليد نسخة ATS-friendly من سيرتك لكل إعلان بمفتاح Gemini الخاص بك، مع بديل تلقائي عند نفاد الحصة اليومية.",
"features.f5t": "إرسال من بريدك مباشرة",
"features.f5d": "الإرسال يتم من حساب Gmail الخاص بك بعد تسجيل دخول آمن لمرة واحدة، بسقف يومي يحمي سمعة بريدك.",
"features.f6t": "خصوصية وقفل كامل",
"features.f6d": "ترخيص موقّع رقميًا لجهاز واحد، وملف الإعدادات وقاعدة البيانات مشفّران (AES-256) ولا يعملان خارج جهازك.",
"how.h2": "أربع خطوات وتعمل بشكل يومي",
"how.s1t": "ثبّت البرنامج",
"how.s1d": "ملف تثبيت واحد لنظام ويندوز، يضع أيقونة على سطح المكتب. لا يحتاج أي خبرة تقنية.",
"how.s2t": "انسخ كود الآلة",
"how.s2d": "عند أول تشغيل تظهر نافذة التفعيل وفيها كود جهازك — انسخه بزر واحد وأرسله لنا واتساب.",
"how.s3t": "الصق مفتاح الترخيص",
"how.s3d": "نرد عليك بمفتاح صالح لجهازك فقط. الصقه واضغط تفعيل — يعمل أوفلاين ولا يحتاج إنترنت للتفعيل نفسه.",
"how.s4t": "سجّل بياناتك مرة واحدة",
"how.s4d": "من الإعدادات: بريد Gmail، مفتاح Gemini، بيانات تيليجرام، كلمات البحث — تُحفظ مشفّرة وتبدأ التشغيل اليومي.",
"how.card_t": "Job Terminator — التفعيل",
"how.card_d": "للتفعيل أرسل <b>كود الآلة</b> التالي على واتساب، ثم الصق <b>مفتاح الترخيص</b> الذي يصلك:",
"how.card_wa": "تواصل واتساب:",
"how.card_btn": "تفعيل",
"pricing.h2": "ترخيص واحد، جهاز واحد، دفع مرة واحدة في السنة",
"pricing.sub": "لا اشتراك شهري في البرنامج. الخدمات الخارجية (حصة Gemini المجانية تكفي للاستخدام اليومي المعتاد) تبقى على حساباتك الخاصة.",
"pricing.p1n": "ترخيص سنوي — جهاز واحد",
"pricing.p1p": "يُحدد عند التواصل",
"pricing.per": "/ سنة",
"pricing.p1i1": "تفعيل لجهاز واحد بكود آلة خاص بك",
"pricing.p1i2": "كل الوحدات: بحث، مطابقة، توليد، إرسال",
"pricing.p1i3": "التحديثات خلال سنة الترخيص",
"pricing.p1i4": "مساعدة في الإعداد لأول مرة",
"pricing.cta_wa": "اطلب عبر واتساب",
"pricing.p2n": "تجديد أو نقل جهاز",
"pricing.p2p": "عند الطلب",
"pricing.p2i1": "تجديد سنة جديدة بنفس الآلية",
"pricing.p2i2": "نقل الترخيص لجهاز جديد بمفتاح جديد",
"pricing.p2i3": "إلغاء المفتاح القديم عند النقل",
"pricing.cta_form": "املأ نموذج الطلب",
"form.label": "نموذج طلب مفتاح الترخيص",
"form.h3": "نموذج طلب مفتاح الترخيص",
"form.hint": "املأ البيانات التالية وسيُرسل طلبك مباشرة على واتساب مع كود الآلة جاهزًا.",
"form.name": "الاسم",
"form.name_ph": "الاسم الكريم",
"form.email": "البريد الإلكتروني",
"form.mid": "كود الآلة (انسخه من نافذة التفعيل)",
"form.mid_ph": "مثال: 85A026046F2FC4B4",
"form.mid_t": "16 حرفًا من نافذة التفعيل",
"form.notes": "ملاحظات",
"form.notes_ph": "اختياري: أي تفاصيل إضافية",
"form.submit": "تجهيز رسالة الطلب",
"download.h2": "ملف واحد يثبّت كل شيء",
"download.meta": "حوالي 96 ميجابايت • Windows 10 / 11 ‏(64-bit)",
"download.d1": "حمّله من زر التحميل وثبّته كأي برنامج ويندوز. ستجد أيقونة Job Terminator على سطح المكتب، وأول تشغيل يفتح نافذة التفعيل مباشرة.",
"download.cta": "تحميل البرنامج الآن",
"download.note": "عند أول تثبيت قد تظهر رسالة حماية من Windows — رسالة معتادة لأي برنامج جديد: اختر «مزيد من المعلومات» ثم «تشغيل على أي حال».",
"download.st1": "حمّل <b>JobTerminatorSetup.exe</b> بزر التحميل",
"download.st2": "ثبّت وافتح البرنامج من أيقونة سطح المكتب",
"download.st3": "انسخ <b>كود الآلة</b> وأرسله واتساب",
"download.st4": "الصق <b>مفتاح الترخيص</b> واضغط تفعيل",
"download.st5": "سجّل بياناتك من <b>الإعدادات</b> وابدأ",
"faq.h2": "كل ما يسأل عنه المشترون عادة",
"faq.q1": "هل يمكن نسخ البرنامج أو المفتاح لجهاز آخر؟",
"faq.a1": "لا. المفتاح موقّع رقميًا ومربوط بكود جهازك، وملف الإعدادات مشفّر بمفتاح مشتق من جهازك وترخيصك — نسخه لجهاز آخر لن يعمل هناك. أي محاولة تعديل على ملفات البرنامج ستُكتشف عند التحقق.",
"faq.q2": "هل تصل بياناتي أو مفاتيحي إليكم؟",
"faq.a2": "لا. مفاتيح Gemini وجوجل وتيليجرام تُدخل على جهازك وتُحفظ مشفّرة عليه. الشيء الوحيد الذي نستلمه هو كود الآلة (16 حرفًا) لإصدار مفتاحك.",
"faq.q3": "هل يحتاج البرنامج إنترنت دائم؟",
"faq.a3": "يحتاج إنترنت للبحث والإرسال والتوليد فقط. التفعيل نفسه يعمل أوفلاين، والترخيص يُتحقق محليًا عند كل تشغيل دون الاتصال بأي سيرفر.",
"faq.q4": "ماذا يحدث عند انتهاء جلسة Gmail أو Telegram؟",
"faq.a4": "من الإعدادات ستجد زري «تسجيل خروج جوجل» و«تسجيل خروج تيليجرام» — يمسحان الجلسة القديمة من داخل البرنامج، ثم تسجّل الدخول من جديد (سيُطلب كود تيليجرام جديد). لا حاجة لحذف أي ملفات يدويًا.",
"faq.q5": "وماذا لو نفدت حصة Gemini اليومية؟",
"faq.a5": "البرنامج يجرب بديل OpenAI تلقائيًا إن أدخلت مفتاحه، ثم ينتقل لقالب احترافي جاهز (رسالة كاملة للإيميل، وقالب مختصر للواتساب) — فلا يتوقف الإرسال ولا تُرسل رسالة فارغة أبدًا.",
"faq.q6": "هل إرسال الواتساب آمن على رقمي؟",
"faq.a6": "الإرسال يتم عبر WhatsApp Web المرتبط برقمك، بسقف يومي وفواصل طويلة وتنويع تلقائي للنص لتقليل مخاطر الحظر. ومع ذلك نوصي بالاعتماد الأساسي على الإيميل للكميات الكبيرة.",
"faq.q7": "غيّرت جهازي — ماذا أفعل؟",
"faq.a7": "أرسل كود الآلة الجديد على واتساب وسنصدر لك مفتاحًا جديدًا ونلغي القديم.",
"footer.desc": "نظام التقديم التلقائي على الوظائف — نسخة ويندوز مرخّصة لجهاز واحد.",
"footer.nav": "روابط",
"footer.contact": "الدعم وطلبات الترخيص واتساب:",
"footer.rights": "© Job Terminator — جميع الحقوق محفوظة.",
"wa.float": "تواصل واتساب",
"wa.orderMsg": "السلام عليكم، أريد مفتاح Job Terminator. كود الآلة الخاص بي: ",
"wa.floatMsg": "السلام عليكم، أريد مفتاح Job Terminator.",
"form.waIntro": "السلام عليكم، أريد مفتاح Job Terminator.\n",
"form.mailSubject": "Job Terminator license request - ",
"form.fName": "Name", "form.fEmail": "Email",
"form.fMid": "Machine code", "form.fNotes": "Notes",
"theme.toLight": "التبديل إلى الوضع الفاتح",
"theme.toDark": "التبديل إلى الوضع الداكن",
"a11y.skip": "تخطَّ إلى المحتوى"
},
en: {
"meta.title": "Job Terminator — Automatic Job Application System | Windows Edition",
"meta.desc": "Job Terminator searches job sites and Telegram channels, matches jobs to your CV, generates a tailored resume per job, and sends from your email — with a single-machine license and data encrypted on your PC.",
"brand.sub": "for Windows",
"nav.label": "Main navigation",
"nav.features": "Features",
"nav.how": "How it works",
"nav.pricing": "License",
"nav.download": "Download",
"nav.faq": "FAQ",
"nav.cta": "Get licensed",
"nav.toggle": "Menu",
"hero.eyebrow": "Licensed Windows edition — one machine",
"hero.title": "Apply to the right jobs, <span class=\"accent\">automatically every day</span>",
"hero.lead": "Job Terminator searches job sites and your Telegram channels, picks the jobs that match your CV, generates a tailored resume for each one, and sends from your email. Your data and keys stay encrypted on your PC and never leave it.",
"hero.cta1": "Get your license key",
"hero.cta2": "Download for Windows",
"hero.meta1": "Windows 10 / 11 (64-bit)",
"hero.meta2": "Offline activation, key locked to one PC",
"hero.meta3": "No monthly subscription",
"mock.title": "Job Terminator — Dashboard",
"mock.s1": "Search", "mock.s2": "Matching", "mock.s3": "Sending",
"mock.s4": "Log", "mock.s5": "Settings",
"mock.st1": "jobs today", "mock.st2": "strong matches", "mock.st3": "sent",
"mock.c1": "87% match", "mock.c2": "76% match",
"mock.c3": "Sent", "mock.c4": "Skipped",
"strip.label": "Works with the tools you already use",
"strip.more": "+ 4 more sites",
"kicker.features": "<span class=\"kicker-num\">01</span>What it does",
"kicker.how": "<span class=\"kicker-num\">02</span>From install to first send",
"kicker.pricing": "<span class=\"kicker-num\">03</span>License & pricing",
"kicker.download": "<span class=\"kicker-num\">04</span>Download & install",
"kicker.faq": "<span class=\"kicker-num\">05</span>FAQ",
"features.h2": "The full application cycle, from search to send",
"features.sub": "Six modules working together. Configure once in Settings, then run daily with one click.",
"features.f1t": "Full job-site coverage",
"features.f1d": "Automatic scan of ten job sites with your keywords and locations, with dedup and per-search history.",
"features.f2t": "Telegram job capture",
"features.f2d": "Connects your channels and groups with your own account and captures new postings in the same cycle.",
"features.f3t": "Smart CV matching",
"features.f3d": "A fit score per job with an adjustable threshold and automatic exclusion of unsuitable levels and fields before anything is sent.",
"features.f4t": "A tailored resume per job",
"features.f4d": "Generates an ATS-friendly version of your CV per posting with your own Gemini key, with automatic fallback when the daily quota runs out.",
"features.f5t": "Send from your own email",
"features.f5d": "Sending happens from your Gmail account after a one-time secure login, with a daily cap that protects your sender reputation.",
"features.f6t": "Full privacy & lock-in",
"features.f6d": "Digitally signed license for one machine; settings file and database encrypted (AES-256) and unusable outside your PC.",
"how.h2": "Four steps and you run daily",
"how.s1t": "Install the program",
"how.s1d": "One installer for Windows that adds a desktop icon. No technical skills needed.",
"how.s2t": "Copy your machine code",
"how.s2d": "On first launch the activation window shows your machine code — copy it in one click and send it to us on WhatsApp.",
"how.s3t": "Paste the license key",
"how.s3d": "We reply with a key valid for your machine only. Paste it and hit activate — activation itself works offline.",
"how.s4t": "Register your data once",
"how.s4d": "In Settings: Gmail, Gemini key, Telegram data, search keywords — stored encrypted, then daily runs begin.",
"how.card_t": "Job Terminator — Activation",
"how.card_d": "To activate, send the following <b>machine code</b> on WhatsApp, then paste the <b>license key</b> you receive:",
"how.card_wa": "WhatsApp:",
"how.card_btn": "Activate",
"pricing.h2": "One license, one machine, pay once a year",
"pricing.sub": "No monthly subscription. External services (the free Gemini quota covers normal daily use) stay on your own accounts.",
"pricing.p1n": "Annual license — one machine",
"pricing.p1p": "Priced on contact",
"pricing.per": "/ year",
"pricing.p1i1": "Activation for one machine with your own code",
"pricing.p1i2": "All modules: search, matching, generation, sending",
"pricing.p1i3": "Updates during the license year",
"pricing.p1i4": "Help with first-time setup",
"pricing.cta_wa": "Order on WhatsApp",
"pricing.p2n": "Renewal or machine transfer",
"pricing.p2p": "On request",
"pricing.p2i1": "Renew for a new year, same process",
"pricing.p2i2": "Move the license to a new machine with a new key",
"pricing.p2i3": "Old key cancelled on transfer",
"pricing.cta_form": "Fill the request form",
"form.label": "License key request form",
"form.h3": "License key request form",
"form.hint": "Fill in the details below and your request will go straight to WhatsApp with the machine code ready.",
"form.name": "Name",
"form.name_ph": "Your name",
"form.email": "Email",
"form.mid": "Machine code (copy it from the activation window)",
"form.mid_ph": "e.g. 85A026046F2FC4B4",
"form.mid_t": "16 characters from the activation window",
"form.notes": "Notes",
"form.notes_ph": "Optional: anything else",
"form.submit": "Prepare the request",
"download.h2": "One file installs everything",
"download.meta": "About 96 MB • Windows 10 / 11 (64-bit)",
"download.d1": "Download it from the button and install like any Windows program. You will find a Job Terminator icon on the desktop, and the first launch opens the activation window directly.",
"download.cta": "Download now",
"download.note": "On first install Windows may show a protection message — normal for any new program: choose “More info”, then “Run anyway”.",
"download.st1": "Download <b>JobTerminatorSetup.exe</b> with the button",
"download.st2": "Install and open it from the desktop icon",
"download.st3": "Copy the <b>machine code</b> and send it on WhatsApp",
"download.st4": "Paste the <b>license key</b> and hit activate",
"download.st5": "Register your data in <b>Settings</b> and start",
"faq.h2": "What buyers usually ask",
"faq.q1": "Can the program or key be copied to another PC?",
"faq.a1": "No. The key is digitally signed and bound to your machine code, and the settings file is encrypted with a key derived from your machine and license — copied elsewhere it will not work. Any tampering with program files is detected on verification.",
"faq.q2": "Do you receive my data or keys?",
"faq.a2": "No. Gemini, Google and Telegram keys are entered on your PC and stored encrypted there. The only thing we receive is the machine code (16 characters) to issue your key.",
"faq.q3": "Does it need the internet all the time?",
"faq.a3": "Internet is needed only for search, sending and generation. Activation itself works offline, and the license is verified locally on every launch with no server involved.",
"faq.q4": "What if my Gmail or Telegram session expires?",
"faq.a4": "In Settings you will find “Logout Google” and “Logout Telegram” buttons — they clear the old session inside the program, then you log in again (a new Telegram code will be requested). No manual file deletion needed.",
"faq.q5": "What if the daily Gemini quota runs out?",
"faq.a5": "The program automatically tries the OpenAI fallback if you entered its key, then switches to a ready professional template (full message for email, short one for WhatsApp) — sending never stops and no empty message is ever sent.",
"faq.q6": "Is WhatsApp sending safe for my number?",
"faq.a6": "Sending goes through WhatsApp Web linked to your number, with a daily cap, long pauses and automatic text variation to reduce ban risk. Still, we recommend email as the primary channel for large volumes.",
"faq.q7": "I changed my PC — what now?",
"faq.a7": "Send the new machine code on WhatsApp and we will issue a new key and cancel the old one.",
"footer.desc": "Automatic job application system — licensed Windows edition for one machine.",
"footer.nav": "Links",
"footer.contact": "Support & license requests on WhatsApp:",
"footer.rights": "© Job Terminator — All rights reserved.",
"wa.float": "Chat on WhatsApp",
"wa.orderMsg": "Hello, I need a Job Terminator license key. My machine code is: ",
"wa.floatMsg": "Hello, I want a Job Terminator license.",
"form.waIntro": "Hello, I need a Job Terminator license key.\n",
"form.mailSubject": "Job Terminator license request - ",
"form.fName": "Name", "form.fEmail": "Email",
"form.fMid": "Machine code", "form.fNotes": "Notes",
"theme.toLight": "Switch to light mode",
"theme.toDark": "Switch to dark mode",
"a11y.skip": "Skip to content"
}
};
