/* Job Terminator V2 dictionaries: Arabic (default, RTL) + English (LTR).
   Every visible string on the page lives here. To add a language, copy the
   "en" block, translate the values, keep the keys, and add a button in the
   masthead language switch with data-lang="<code>" plus its entry in LANGUAGES
   in script.js. No other code changes are required. */
const I18N = {
ar: {
"meta.title": "Job Terminator — البرنامج الذي يقدّم على الوظائف بدلًا عنك | نسخة ويندوز",
"meta.desc": "توقّف عن التقديم اليدوي ساعةً كل يوم. Job Terminator يبحث في مواقع التوظيف الرئيسية، يطابق الوظائف مع سيرتك، يكتب سيرة مخصصة لكل إعلان، ويرسل من بريدك — كل يوم، وأنت لا تفتح متصفحًا. ترخيص لجهاز واحد وبياناتك مشفّرة على جهازك.",
"brand.sub": "للويندوز",
"nav.label": "التنقل الرئيسي",
"nav.features": "المميزات",
"nav.how": "طريقة التشغيل",
"nav.pricing": "الترخيص",
"nav.download": "التحميل",
"nav.faq": "الأسئلة الشائعة",
"nav.cta": "اطلب مفتاحك",
"nav.toggle": "القائمة",
"hero.eyebrow": "نسخة ويندوز مرخّصة، لجهاز واحد",
"hero.title": "توقّف عن البحث عن وظيفة. <span class=\"accent\">دعه يبحث ويقدّم بدلًا عنك</span>",
"hero.lead": "Job Terminator يقرأ إعلانات الوظائف في مواقع التوظيف الرئيسية، يقيس توافق كل واحدة مع سيرتك، يكتب نسخة مخصّصة لكل إعلان، ويرسلها من بريدك أنت. تشغّله مرة، فيعمل كل يوم — ومفاتيحك وبياناتك تبقى مشفّرة على جهازك.",
"hero.cta1": "ابدأ الليلة — اطلب المفتاح",
"hero.cta2": "حمّل نسخة ويندوز",
"hero.meta1": "Windows 10 / 11 (64-bit)",
"hero.meta2": "تفعيل أوفلاين بمفتاح لجهاز واحد",
"hero.meta3": "بلا اشتراك شهري في البرنامج",
"cap.hero": "ذراع آلي يشتغل على طلباتك بسرعة الآلة.",
"cap.hero.alt": "ذراع آلي أسود ومعدني يدفع ورقة سيرة ذاتية نحو صينية إخراج، مع وميض ضوء زمردي.",
"cap.desk": "يفتح المواقع الرئيسية في دورة واحدة، بسرعة وبلا تكرار.",
"cap.desk.alt": "ذراع آلي يحرّك مجموعة أوراق سيرة ذاتية بسرعة على سطح عمل داكن، مع شرارات ضوء زمردية.",
"cap.steps": "مسار آلي سريع من البحث إلى الإرسال.",
"cap.steps.alt": "ذراع آلي يمرّ بسرعة على أربع صواني ويسقط ورقة سيرة ذاتية في كل واحدة، مع وميض زمردي.",
"cap.night": "يعمل وحده طوال الليل.",
"cap.night.alt": "ذراع آلي صغير يعالج أوراق سيرة ذاتية وحده في غرفة مظلمة، مع وهج زمردي عند ملقطه.",
"cap.key.alt": "ملقط آلي يرفع ورقة سيرة ذاتية بوميض ضوء زمردي.",
"wire.label": "التكاملات",
"strip.label": "يعمل مع الأدوات التي تستخدمها أصلًا",
"strip.more": "تشفير AES-256",
"features.h2": "كل الطريق من البحث إلى الإرسال — بدونك",
"features.sub": "ست وحدات تعمل كفريق واحد: تجد، تطابق، تكتب، وترسل. أنت فقط تفتح السجل.",
"features.f1t": "٤ مواقع توظيف تُقرأ قبل قهوتك",
"features.f1d": "بحث تلقائي في المواقع الرئيسية (Wuzzuf، Bayt، Wazafny، GulfTalent) بالكلمات والمواقع التي تحددها، بلا تكرار، ومع حفظ لكل نتيجة.",
"features.f2t": "وظيفة جديدة؟ وصلت قبل أن تمرّ",
"features.f2d": "دورة بحث كاملة تجمع كل إعلان حديث في وقت واحد، فتجد الجديد أولاً بأول دون الانتظار حتى اليوم التالي.",
"features.f3t": "درجة توافق قبل أن تُهدر سيرة",
"features.f3d": "رقم لكل وظيفة، وعتبة تضبطها بنفسك، واستبعاد تلقائي لما لا يشبهك.",
"features.f4t": "سيرة تُكتب من جديد لكل وظيفة. تلقائيًا.",
"features.f4d": "نسخة ATS-friendly لكل إعلان بمفتاح Gemini الخاص بك، مع بديل جاهز إن نفدت الحصة.",
"features.f5t": "الرسالة تخرج من بريدك أنت",
"features.f5d": "إرسال من Gmail بعد دخول آمن لمرة واحدة، بسقف يومي يحمي سُمعتك.",
"features.f6t": "بياناتك لا تفارق جهازك",
"features.f6d": "ترخيص موقّع رقميًا لجهاز واحد، وملف الإعدادات وقاعدة البيانات مشفّران AES-256.",
"log.title": "سجل التشغيل — نموذج",
"log.note": "شكل السجل اليومي داخل البرنامج. صفوف توضيحية، وليست نتائج حقيقية.",
"log.caption": "سجل تشغيل توضيحي: الوظيفة، المصدر، درجة المطابقة، الحالة.",
"log.col1": "الوظيفة",
"log.col2": "المصدر",
"log.col3": "المطابقة",
"log.col4": "الحالة",
"log.filter.label": "تصفية السجل",
"log.filter.all": "الكل",
"log.filter.strong": "مطابقة قوية",
"log.filter.sent": "أُرسلت",
"log.filter.skip": "مستبعدة",
"log.t1": "مهندس تخطيط، بنية تحتية",
"log.t2": "Planning Engineer, Roads",
"log.t3": "مهندس مكتب فني، مقاولات",
"log.t4": "Site Engineer, Infra",
"log.t5": "Junior QA، خارج المجال",
"log.t6": "Sales Representative",
"log.s1": "مطابقة قوية",
"log.s2": "تم الإرسال",
"log.s3": "مستبعدة",
"log.empty": "لا توجد صفوف بهذه الحالة في السجل.",
"pq.text": "الفرص لا تذهب لمن يقدّم أكثر، بل لمن يقدّم أولًا.",
"pq.attr": "Job Terminator",
"pq.role": "فكرة البرنامج",
"how.h2": "من التثبيت إلى أول تقديم — أربع خطوات",
"how.s1t": "ثبّته",
"how.s1d": "ملف واحد لنظام ويندوز، وأيقونة على سطح المكتب. بلا خبرة تقنية.",
"how.s2t": "انسخ كود جهازك",
"how.s2d": "نافذة التفعيل تعرض الكود: انسخه وابعته واتساب.",
"how.s3t": "الصق مفتاحك",
"how.s3d": "نرسل مفتاحًا لجهازك وحده. يعمل أوفلاين، بلا سيرفر.",
"how.s4t": "سجّل بياناتك مرة واحدة",
"how.s4d": "Gmail، مفتاح Gemini، كلمات البحث والمواقع — تُحفظ مشفّرة ويبدأ العمل.",
"how.card_t": "Job Terminator، التفعيل",
"how.card_d": "للتفعيل أرسل <b>كود الآلة</b> التالي على واتساب، ثم الصق <b>مفتاح الترخيص</b> الذي يصلك:",
"how.card_wa": "تواصل واتساب:",
"how.card_btn": "تفعيل",
"pricing.h2": "دفعة واحدة في السنة. ترخيص واحد. جهاز واحد.",
"pricing.sub": "بلا اشتراك شهري. الخدمات الخارجية تبقى على حساباتك، والحصة المجانية من Gemini تكفي الاستخدام اليومي المعتاد.",
"pricing.p1n": "ترخيص سنوي — جهاز واحد",
"pricing.p1p": "يُحدد عند التواصل",
"pricing.per": "/ سنة",
"pricing.p1i1": "تفعيل بجهازك أنت وكود خاص بك",
"pricing.p1i2": "كل الوحدات: بحث، مطابقة، كتابة، إرسال",
"pricing.p1i3": "التحديثات طوال سنة الترخيص",
"pricing.p1i4": "مساعدة في الإعداد أول مرة",
"pricing.cta_wa": "اطلبه على واتساب",
"pricing.p2n": "تجديد أو نقل لجهاز جديد",
"pricing.p2p": "عند الطلب",
"pricing.p2i1": "تجديد سنة جديدة بنفس الطريقة",
"pricing.p2i2": "نقل الترخيص لجهاز جديد بمفتاح جديد",
"pricing.p2i3": "إلغاء المفتاح القديم فورًا عند النقل",
"pricing.cta_form": "اطلب من النموذج",
"form.label": "نموذج طلب مفتاح الترخيص",
"form.h3": "اطلب مفتاحك في أقل من دقيقة",
"form.hint": "املأ البيانات وسيتجهّز طلبك مع كود جهازك جاهزًا للإرسال.",
"form.name": "الاسم",
"form.name_ph": "الاسم الكريم",
"form.email": "البريد الإلكتروني",
"form.email_ph": "you@email.com",
"form.mid": "كود الآلة (انسخه من نافذة التفعيل)",
"form.mid_ph": "مثال: 85A026046F2FC4B4",
"form.mid_t": "16 حرفًا من نافذة التفعيل",
"form.notes": "ملاحظات",
"form.notes_ph": "اختياري: أي تفاصيل إضافية",
"form.submit": "جهّز رسالة الطلب",
"form.err.required": "هذا الحقل مطلوب.",
"form.err.email": "أدخل بريدًا إلكترونيًا صحيحًا.",
"form.err.mid": "كود الآلة 16 حرفًا من نافذة التفعيل.",
"form.err.fix": "راجع الحقول المظللة ثم أعد المحاولة.",
"form.ok": "تم تجهيز رسالة الطلب. أكمل الإرسال في النافذة التي فُتحت.",
"download.h2": "ملف واحد، ويبدأ العد",
"download.meta": "حوالي 81 ميجابايت • Windows 10 / 11 (64-bit)",
"download.d1": "حمّله وثبّته كأي برنامج ويندوز. أول تشغيل يفتح نافذة التفعيل مباشرة.",
"download.cta": "حمّل Job Terminator الآن",
"download.note": "عند أول تثبيت قد تظهر رسالة حماية من Windows، رسالة معتادة لأي برنامج جديد: اختر «مزيد من المعلومات» ثم «تشغيل على أي حال».",
"download.st1": "حمّل <b>JobTerminatorSetup.exe</b>",
"download.st2": "ثبّته وافتحه من سطح المكتب",
"download.st3": "انسخ <b>كود الآلة</b> وابعته واتساب",
"download.st4": "الصق <b>مفتاح الترخيص</b> واضغط تفعيل",
"download.st5": "سجّل بياناتك في <b>الإعدادات</b> واتركه يعمل",
"faq.h2": "أسئلة يسألها كل مشتري قبل الدفع",
"faq.q1": "هل يمكن نسخ البرنامج أو المفتاح لجهاز آخر؟",
"faq.a1": "لا. المفتاح موقّع رقميًا ومربوط بكود جهازك، وملف الإعدادات مشفّر بمفتاح مشتق من جهازك وترخيصك، ونسخه لجهاز آخر لن يعمل هناك. أي محاولة تعديل على ملفات البرنامج ستُكتشف عند التحقق.",
"faq.q2": "هل تصل بياناتي أو مفاتيحي إليكم؟",
"faq.a2": "لا. مفاتيح Gemini وجوجل تُدخل على جهازك وتُحفظ مشفّرة عليه. الشيء الوحيد الذي نستلمه هو كود الآلة (16 حرفًا) لإصدار مفتاحك.",
"faq.q3": "هل يحتاج البرنامج إنترنت دائم؟",
"faq.a3": "يحتاج إنترنت للبحث والإرسال والتوليد فقط. التفعيل نفسه يعمل أوفلاين، والترخيص يُتحقق محليًا عند كل تشغيل دون الاتصال بأي سيرفر.",
"faq.q4": "ماذا يحدث عند انتهاء جلسة Gmail؟",
"faq.a4": "من الإعدادات ستجد زر «تسجيل خروج جوجل»، يمسح الجلسة القديمة من داخل البرنامج، ثم تسجّل الدخول من جديد. لا حاجة لحذف أي ملفات يدويًا.",
"faq.q5": "وماذا لو نفدت حصة Gemini اليومية؟",
"faq.a5": "البرنامج ينتقل لقالب احترافي جاهز (رسالة كاملة للإيميل)، فلا يتوقف الإرسال ولا تُرسل رسالة فارغة أبدًا.",
"faq.q6": "ما المواقع التي يدعمها البرنامج؟",
"faq.a6": "النسخة العامة تعمل على Wuzzuf وBayt وWazafny وGulfTalent، وتختار منها ما تريد في الإعدادات — مع بحث بلا تكرار وسجل كامل لكل نتيجة.",
"faq.q7": "غيّرت جهازي، ماذا أفعل؟",
"faq.a7": "أرسل كود الآلة الجديد على واتساب وسنصدر لك مفتاحًا جديدًا ونلغي القديم.",
"faq.a7": "أرسل كود الآلة الجديد على واتساب وسنصدر لك مفتاحًا جديدًا ونلغي القديم.",
"band.label": "خصوصية البيانات",
"band.line": "بياناتك على جهازك. المفتاح لجهاز واحد. والبريد يبقى بريدك أنت.",
"footer.desc": "نظام تقديم تلقائي على الوظائف، نسخة ويندوز مرخّصة لجهاز واحد.",
"footer.nav": "روابط",
"footer.contact": "الدعم وطلبات الترخيص واتساب:",
"footer.rights": "Job Terminator، جميع الحقوق محفوظة.",
"wa.float": "تواصل واتساب",
"wa.orderMsg": "السلام عليكم، أريد مفتاح Job Terminator. كود الآلة الخاص بي: ",
"wa.floatMsg": "السلام عليكم، أريد مفتاح Job Terminator.",
"form.waIntro": "السلام عليكم، أريد مفتاح Job Terminator.\n",
"form.mailSubject": "Job Terminator license request - ",
"form.fName": "الاسم",
"form.fEmail": "البريد الإلكتروني",
"form.fMid": "كود الآلة",
"form.fNotes": "ملاحظات",
"theme.toLight": "التبديل إلى الوضع الفاتح",
"theme.toDark": "التبديل إلى الوضع الداكن",
"a11y.skip": "تخطَّ إلى المحتوى",
"log.updated": "آخر تحديث",
"form.storage": "يُحفظ كل طلب في سجل محلي على هذا الجهاز مع وقته، ويمكن تصديره من زر السجل أسفل النموذج.",
"form.stored": "تم حفظ الطلب محليًا في هذا الجهاز. أكمل الإرسال في النافذة التي فُتحت.",
"footer.updated": "آخر تحديث للموقع",
"orders.title": "سجل طلبات الترخيص",
"orders.open": "سجل الطلبات",
"orders.csv": "تصدير CSV",
"orders.json": "تصدير JSON",
"orders.clear": "مسح السجل",
"orders.close": "إغلاق",
"orders.empty": "لا توجد طلبات محفوظة على هذا الجهاز بعد.",
"orders.note": "تُحفظ الطلبات محليًا في هذا المتصفح فقط، مع وقت كل طلب، ويمكن تصديرها كملف. أرسل الطلب على واتساب أو بالبريد ليكتمل التسجيل لدى الفريق.",
"orders.count": "عدد الطلبات:",
"orders.confirmClear": "هل تريد مسح كل الطلبات المحفوظة على هذا الجهاز؟ لا يمكن التراجع.",
"orders.cleared": "تم مسح السجل.",
"orders.saved": "تم تنزيل ملف السجل.",
"orders.field.time": "الوقت",
"orders.field.name": "الاسم",
"orders.field.email": "البريد",
"orders.field.mid": "كود الآلة",
"orders.field.notes": "ملاحظات",
"orders.field.lang": "اللغة",
"hooks.label": "نفس الوظيفة، بلا الوجع",
"hooks.h1f": "٣ ساعات تقديم كل مساء",
"hooks.h1t": "صفر. كل يوم.",
"hooks.h2f": "سيرة واحدة تُرسل للجميع",
"hooks.h2t": "سيرة مخصّصة لكل إعلان",
"hooks.h3f": "٤٠ تبويبًا وخمسة مواقع مفتوحة",
"hooks.h3t": "زر واحد، والباقي يعمل",
},
en: {
"meta.title": "Job Terminator — the app that applies for jobs while you live your life | Windows",
"meta.desc": "Stop spending an hour a day applying by hand. Job Terminator searches the main job boards, matches jobs to your CV, writes a tailored résumé for each posting, and sends from your own inbox — daily, without opening a browser. One-machine license, data encrypted on your PC.",
"brand.sub": "for Windows",
"nav.label": "Main navigation",
"nav.features": "Features",
"nav.how": "How it works",
"nav.pricing": "License",
"nav.download": "Download",
"nav.faq": "FAQ",
"nav.cta": "Get your key",
"nav.toggle": "Menu",
"hero.eyebrow": "Licensed Windows edition, one machine",
"hero.title": "Stop hunting for jobs. <span class=\"accent\">Let it hunt and apply for you</span>",
"hero.lead": "Job Terminator reads job postings across the main job boards, scores each one against your CV, writes a tailored version for every posting, and sends from your own inbox. Set it up once, and it runs every day — while your keys and data stay encrypted on your PC.",
"hero.cta1": "Start tonight — get your key",
"hero.cta2": "Download for Windows",
"hero.meta1": "Windows 10 / 11 (64-bit)",
"hero.meta2": "Offline activation, key locked to one PC",
"hero.meta3": "No monthly subscription",
"cap.hero": "A robotic arm working your applications at machine speed.",
"cap.hero.alt": "A black and metal robotic arm pushing a CV sheet into an out-tray, with an emerald flash of light.",
"cap.desk": "The main job boards cleared in one pass — fast, and never twice.",
"cap.desk.alt": "A robotic arm sweeping a fan of CV sheets fast across a dark work surface, with emerald light sparks.",
"cap.steps": "A fast automated path from search to send.",
"cap.steps.alt": "A robotic arm moving fast along four trays, dropping a CV sheet into each, with an emerald flash.",
"cap.night": "It works alone all night.",
"cap.night.alt": "A compact robotic arm processing CV sheets alone in a dark room, with an emerald glow at its gripper.",
"cap.key.alt": "A robotic gripper lifting a CV sheet with a burst of emerald light.",
"wire.label": "Integrations",
"strip.label": "Works with the tools you already use",
"strip.more": "AES-256 encryption",
"features.h2": "The whole road from search to send — without you",
"features.sub": "Six modules working as one team: find, match, write, send. You just read the log.",
"features.f1t": "4 job boards read before your coffee",
"features.f1d": "An automatic scan across the main boards you choose (Wuzzuf, Bayt, Wazafny, GulfTalent), de-duplicated, with every result saved.",
"features.f2t": "A new posting? Caught before it scrolls away",
"features.f2d": "A full cycle grabs every fresh posting at once, so you see what's new right away — without waiting until the next day.",
"features.f3t": "A match score before you waste a résumé",
"features.f3d": "A score per job, a threshold you set yourself, and automatic exclusion of what doesn't fit.",
"features.f4t": "A résumé rewritten for every job. Automatically.",
"features.f4d": "An ATS-friendly version for each posting using your own Gemini key, with a ready fallback when the quota runs out.",
"features.f5t": "The message leaves from your own inbox",
"features.f5d": "Sent from your Gmail after a one-time secure login, with a daily cap that protects your reputation.",
"features.f6t": "Your data never leaves your PC",
"features.f6d": "A digitally signed license for one machine; settings file and database encrypted with AES-256.",
"log.title": "Run log — sample",
"log.note": "The shape of the daily log inside the app. Illustrative rows, not real results.",
"log.caption": "Sample run log: job, source, match score, state.",
"log.col1": "Job",
"log.col2": "Source",
"log.col3": "Match",
"log.col4": "State",
"log.filter.label": "Filter the log",
"log.filter.all": "All",
"log.filter.strong": "Strong match",
"log.filter.sent": "Sent",
"log.filter.skip": "Skipped",
"log.t1": "Planning Engineer, Infrastructure",
"log.t2": "Planning Engineer, Roads",
"log.t3": "Technical Office Engineer, Contracting",
"log.t4": "Site Engineer, Infra",
"log.t5": "Junior QA, outside the field",
"log.t6": "Sales Representative",
"log.s1": "Strong match",
"log.s2": "Sent",
"log.s3": "Skipped",
"log.empty": "No rows in this state right now.",
"pq.text": "Opportunities don't go to whoever applies most. They go to whoever shows up first.",
"pq.attr": "Job Terminator",
"pq.role": "the idea behind the app",
"how.h2": "From install to first application — four steps",
"how.s1t": "Install it",
"how.s1d": "One Windows file and a desktop icon. No technical skill needed.",
"how.s2t": "Copy your machine code",
"how.s2d": "The activation window shows the code: copy it and send it on WhatsApp.",
"how.s3t": "Paste your key",
"how.s3d": "We send a key for your machine only. It works offline, with no server.",
"how.s4t": "Register your data once",
"how.s4d": "Gmail, Gemini key, keywords and job boards — stored encrypted, and it begins.",
"how.card_t": "Job Terminator, activation",
"how.card_d": "To activate, send the following <b>machine code</b> on WhatsApp, then paste the <b>license key</b> you receive:",
"how.card_wa": "WhatsApp:",
"how.card_btn": "Activate",
"pricing.h2": "Pay once a year. One license. One machine.",
"pricing.sub": "No monthly subscription. External services stay on your own accounts, and Gemini's free quota covers normal daily use.",
"pricing.p1n": "Annual license — one machine",
"pricing.p1p": "Priced on contact",
"pricing.per": "/ year",
"pricing.p1i1": "Activation on your own machine, with your own code",
"pricing.p1i2": "All modules: search, match, write, send",
"pricing.p1i3": "Updates through the license year",
"pricing.p1i4": "Help with first-time setup",
"pricing.cta_wa": "Order on WhatsApp",
"pricing.p2n": "Renewal or move to a new PC",
"pricing.p2p": "On request",
"pricing.p2i1": "Renew for another year, the same way",
"pricing.p2i2": "Move the license to a new machine with a new key",
"pricing.p2i3": "The old key is cancelled immediately on transfer",
"pricing.cta_form": "Request from the form",
"form.label": "License key request form",
"form.h3": "Get your key in under a minute",
"form.hint": "Fill this in and your request is prepared with your machine code ready to send.",
"form.name": "Name",
"form.name_ph": "Your name",
"form.email": "Email",
"form.email_ph": "you@email.com",
"form.mid": "Machine code (copy it from the activation window)",
"form.mid_ph": "e.g. 85A026046F2FC4B4",
"form.mid_t": "16 characters from the activation window",
"form.notes": "Notes",
"form.notes_ph": "Optional: anything else",
"form.submit": "Prepare the request",
"form.err.required": "This field is required.",
"form.err.email": "Enter a valid email address.",
"form.err.mid": "The machine code is 16 characters from the activation window.",
"form.err.fix": "Check the highlighted fields and try again.",
"form.ok": "Request prepared. Finish sending it in the window that just opened.",
"download.h2": "One file, and the count starts",
"download.meta": "About 81 MB • Windows 10 / 11 (64-bit)",
"download.d1": "Download and install it like any Windows app. The first launch opens the activation window.",
"download.cta": "Download Job Terminator now",
"download.note": "On first install Windows may show a protection message, normal for any new program: choose “More info”, then “Run anyway”.",
"download.st1": "Download <b>JobTerminatorSetup.exe</b>",
"download.st2": "Install it and open it from the desktop",
"download.st3": "Copy the <b>machine code</b> and send it on WhatsApp",
"download.st4": "Paste the <b>license key</b> and hit activate",
"download.st5": "Register your data in <b>Settings</b> and let it run",
"faq.h2": "What every buyer asks before paying",
"faq.q1": "Can the program or key be copied to another PC?",
"faq.a1": "No. The key is digitally signed and bound to your machine code, and the settings file is encrypted with a key derived from your machine and license, so copied elsewhere it will not work. Any tampering with program files is detected on verification.",
"faq.q2": "Do you receive my data or keys?",
"faq.a2": "No. Gemini and Google keys are entered on your PC and stored encrypted there. The only thing we receive is the machine code (16 characters) to issue your key.",
"faq.q3": "Does it need the internet all the time?",
"faq.a3": "Internet is needed only for search, sending and generation. Activation itself works offline, and the license is verified locally on every launch with no server involved.",
"faq.q4": "What if my Gmail session expires?",
"faq.a4": "In Settings you will find a “Logout Google” button, it clears the old session inside the program, then you log in again. No manual file deletion needed.",
"faq.q5": "What if the daily Gemini quota runs out?",
"faq.a5": "The program switches to a ready professional template (a full message for email), so sending never stops and no empty message is ever sent.",
"faq.q6": "Which job boards are supported?",
"faq.a6": "The public edition works with Wuzzuf, Bayt, Wazafny and GulfTalent — choose the ones you want in Settings, with de-duplicated search and a full log of every result.",
"faq.q7": "I changed my PC, what now?",
"faq.a7": "Send the new machine code on WhatsApp and we will issue a new key and cancel the old one.",
"band.label": "Data privacy",
"band.line": "Your data on your machine. One key, one PC. And the inbox stays yours.",
"footer.desc": "Automatic job-application system, licensed Windows edition for one machine.",
"footer.nav": "Links",
"footer.contact": "Support and license requests on WhatsApp:",
"footer.rights": "Job Terminator, all rights reserved.",
"wa.float": "Chat on WhatsApp",
"wa.orderMsg": "Hello, I need a Job Terminator license key. My machine code is: ",
"wa.floatMsg": "Hello, I want a Job Terminator license.",
"form.waIntro": "Hello, I need a Job Terminator license key.\n",
"form.mailSubject": "Job Terminator license request - ",
"form.fName": "Name",
"form.fEmail": "Email",
"form.fMid": "Machine code",
"form.fNotes": "Notes",
"theme.toLight": "Switch to light mode",
"theme.toDark": "Switch to dark mode",
"a11y.skip": "Skip to content",
"log.updated": "Last updated",
"form.storage": "Every request is stored in a local log on this device with its time, and can be exported from the log button below the form.",
"form.stored": "Request saved locally on this device. Finish sending it in the window that just opened.",
"footer.updated": "Site last updated",
"orders.title": "License request log",
"orders.open": "Request log",
"orders.csv": "Export CSV",
"orders.json": "Export JSON",
"orders.clear": "Clear log",
"orders.close": "Close",
"orders.empty": "No requests are stored on this device yet.",
"orders.note": "Requests are stored locally in this browser only, each with its timestamp, and can be exported as a file. Send the request on WhatsApp or by email for the team to record it too.",
"orders.count": "Requests:",
"orders.confirmClear": "Clear all requests stored on this device? This cannot be undone.",
"orders.cleared": "The log has been cleared.",
"orders.saved": "The log file has been downloaded.",
"orders.field.time": "Time",
"orders.field.name": "Name",
"orders.field.email": "Email",
"orders.field.mid": "Machine code",
"orders.field.notes": "Notes",
"orders.field.lang": "Language",
"hooks.label": "Same job hunt, none of the grind",
"hooks.h1f": "3 hours applying every evening",
"hooks.h1t": "Zero. Every day.",
"hooks.h2f": "One résumé blasted at everyone",
"hooks.h2t": "A tailored résumé per posting",
"hooks.h3f": "40 tabs and five sites open",
"hooks.h3t": "One click, and the rest runs",
},
};
